matrix:
  fast_finish: true
  include:
    - language: generic
      os: osx
      osx_image: xcode9.3
 
 before_install:
   - source travis/before_install.sh
 install:
   - "./travis/install.sh"
 script:
   - "./travis/build.sh"
