image: Visual Studio 2015

version: 1.2.5

environment:
  matrix:
  - QT: C:\Qt\5.10.1\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14
    OKJVERSION: 1.2.5

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

install:
  - ps: |
      Write-Host "Installing GStreamer..." -ForegroundColor Cyan
      $msiPath = "$($env:USERPROFILE)\gstreamer.msi"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile('https://gstreamer.freedesktop.org/data/pkg/windows/1.14.0.1/gstreamer-1.0-x86_64-1.14.0.1.msi', $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /package $msiPath /passive ADDLOCAL=ALL
      Write-Host "Installed" -ForegroundColor Green
  - ps: |
      Write-Host "Installing GStreamer dev..." -ForegroundColor Cyan
      $msiPath = "$($env:USERPROFILE)\gstreamer-devel.msi"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile('https://gstreamer.freedesktop.org/data/pkg/windows/1.14.0.1/gstreamer-1.0-devel-x86_64-1.14.0.1.msi', $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /package $msiPath /passive ADDLOCAL=ALL
      Write-Host "Installed" -ForegroundColor Green

build_script:
  - call "appveyor/build_windows.cmd"

artifacts:
  - path: build\windows\msvc\x86_64\release\OpenKJ_$(appveyor_repo_tag_name)_windows_x86_64_portable.zip
    name: portable
  - path: installer\windows\x86_64\OpenKJ_$(appveyor_repo_tag_name)_windows_x86_64_installer.exe
    name: installer
