image: Visual Studio 2015

version: 1.2.6

environment:
  OKJVERSION: {version}
  matrix:
  - TARGET_ARCH: x64
    QT: C:\Qt\5.10.1\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14
    LONGARCH: x86_64
  - TARGET_ARCH: x86
    PLATFORM: x86
    COMPILER: msvc
    VSVER: 14
    LONGARCH: x86

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

install:
  - ps: |
      Write-Host "Installing GStreamer..." -ForegroundColor Cyan
      Write-Host "Platform - $($env:target_arch)"
      $msiPath = "$($env:USERPROFILE)\gstreamer.msi"
      $gstInstallUrl = "https://gstreamer.freedesktop.org/data/pkg/windows/1.14.0.1/gstreamer-1.0-$($env:LONGARCH)-1.14.0.1.msi"
      $gstDevelInstallUrl = "https://gstreamer.freedesktop.org/data/pkg/windows/1.14.0.1/gstreamer-1.0-devel-$($env:LONGARCH)-1.14.0.1.msi"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile($gstInstallUrl, $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /package $msiPath /passive ADDLOCAL=ALL
      Write-Host "Installed" -ForegroundColor Green
  - ps: |
      Write-Host "Installing GStreamer dev..." -ForegroundColor Cyan
      $msiPath = "$($env:USERPROFILE)\gstreamer-devel.msi"
      Write-Host "Downloading..."
      if ($env:target_arch -eq "x86_64")
      (New-Object Net.WebClient).DownloadFile($gstDevelInstallUrl, $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /package $msiPath /passive ADDLOCAL=ALL
      Write-Host "Installed" -ForegroundColor Green

build_script:
  - call "appveyor/build_windows.cmd"

artifacts:
  - path: installer\windows\x86_64\OpenKJ-$(OKJVERSION)-windows-$($env:target_arch)-installer.exe
    name: installer
